name: Deploy to Coolify

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -X POST "http://127.0.0.1:8000/api/v1/deploy?uuid=y1245gqplykoixklexgi0qme&force=true" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}"
